hydra:
  searchpath:
    - file://vendor/verl/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 1024
  max_response_length: 1024
  train_batch_size: 256
  return_raw_chat: True
  shuffle: False

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: vseek_sglang
    multi_turn:
      enable: True
      max_assistant_turns: 3
      format: qwen25
      max_tool_response_length: 1024
    
    max_num_batched_tokens: 65536
    gpu_memory_utilization: 0.75
    max_model_len: 8192
    max_num_seqs: 4096
    n: 5
    over_sample_rate: 0.1
    mode: sync
    calculate_log_probs: False
    log_prob_micro_batch_size_per_gpu: 32
    log_prob_use_dynamic_bsz: False
    log_prob_max_token_len_per_gpu: 32768
    disable_log_stats: False
    multi_stage_wake_up: False
    agent:
      num_workers: 1
      default_agent_loop: single_turn_agent
      agent_loop_config_path: null
    engine_kwargs:
      vllm: 
        mm_processor_cache_gb: 0
      sglang: {}
  actor:
    strategy: fsdp2
    rollout_n: ${actor_rollout_ref.rollout.n}  # REQUIRED: Must match rollout.n
    use_dynamic_bsz: False
    ppo_micro_batch_size_per_gpu: 4  # Required when use_dynamic_bsz is False
    ppo_max_token_len_per_gpu: 32768
    grad_clip: 1.0
    clip_ratio: 0.30
    entropy_coeff: 0.000
    use_kl_loss: False
reward_model:
  reward_manager: naive  # Required by base ppo_trainer config
custom_reward_function:
  path: src/vseek/trainer/reward/vseekreward.py
  name: compute_score
  reward_kwargs:
    format_score: 0.0
    score: {'em':1.0, 'puls': 0.5}
    reward_type: em
    puls_threshold: 0.15

reward_model:
  reward_manager: naive
