[project]
name = "vseek"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.1",
    "tqdm>=4.67.1",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.0.0",
    "ftfy",
    "regex",
    "einops",
    "timm",
    "opencv-python",
    "fvcore",
    "transformers>=4.45.0",
    "torch",
    "torchvision",
    "vllm>=0.10.2",
    "langchain>=0.3.27",
    "v>=1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

