
retriever:
  port: 9000
  server_url: "http://127.0.0.1:${retriever.port}"
  index_path: "/home/hg22723/vseek/dataset"
  topk: 1
  retriever_name: "ViClip"
  retriever_model: "ViClip"
  retrieval_model_path: "/nas/mars/model_weights/viclip/ViClip-InternVid-10M-FLT.pth"
  text_encoder_model_path: "/nas/mars/model_weights/viclip/bpe_simple_vocab_16e6.txt.gz"
  gpu_number: 0
  faiss_gpu: false
  dataset_name: "lvb"
  window_size: 8
  desired_interval_in_sec: 1
llm:
  port: 8001
  server_url: "http://127.0.0.1:${llm.port}/v1"
  model: "Qwen/Qwen2.5-VL-7B-Instruct"
  openai_api_key: "EMPTY"
inference:
  max_image_width: 256
  max_image_height: 256
  image_quality: 90
  temperature: 0.0
  topk: 1
  max_parse_attempts: 3
  max_reasoning_attempts: 5
  output_dir: "output"
  max_images_per_turn: 16
  gpu_number: 0
  max_output_tokens: 512
dataset:
  name: "lvb"
  desired_interval_in_sec: ${retriever.desired_interval_in_sec}
  window_size: ${retriever.window_size}
  dataset_path: "/nas/mars/dataset/longvideobench/LongVideoBench/"
  burned_path: "/nas/mars/dataset/longvideobench/"
  
