


inference:
  max_image_width: 224
  max_image_height: 224
  image_quality: 90
  temperature: 0.5
  topk: 1
  max_parse_attempts: 3
  max_reasoning_attempts: 5
  output_dir: "output"
  max_images_per_turn: 16
  gpu_number: 0
  max_output_tokens: 512

  
tools:
  - class_name: "vseek.tools.search.VideoSearchTool"
    config:
      type: native
      server_url: ${.retriever.server_url}
      timeout: 30
      topk: ${.retriever.topk}
      dataset_name: ${.retriever.dataset_name}
      window_size: ${.retriever.window_size}
      index_path: ${.retriever.index_path}
      cache_limit: 64
      max_frames_per_turn: 16
      video_summary: false
      dataset:
        name: "lvb"
        desired_interval_in_sec: ${..retriever.desired_interval_in_sec}
        window_size: ${..retriever.window_size}
        dataset_path: "/nas/mars/dataset/longvideobench/LongVideoBench/"
        burned_path: "/nas/mars/dataset/longvideobench/"
      retriever:
        port: 9000
        server_url: "http://127.0.0.1:${.port}"
        index_path: "/home/hg22723/vseek/dataset"
        topk: 2
        retriever_name: "ViClip"
        retriever_model: "ViClip"
        retrieval_model_path: "/nas/mars/model_weights/viclip/ViClip-InternVid-10M-FLT.pth"
        text_encoder_model_path: "/nas/mars/model_weights/viclip/bpe_simple_vocab_16e6.txt.gz"
        gpu_number: 0
        faiss_gpu: false
        dataset_name: "lvb"
        window_size: 8
        desired_interval_in_sec: 1
    tool_schema:
      type: function
      function:
        name: video_search
        description: Searches video frames by natural language or subtitle string.
        parameters:
          type: object
          properties:
            query:
              type: string
              description: Text to search. Used for both modes.
            mode:
              type: string
              enum: [base, subtitle]
              description: base for natural language search, subtitle to match subtitles.
          required: [query, mode]

