#!/bin/bash
set -euo pipefail

# Uses JSONs prepared by:
#   1_prepare_videotree_data_from_vseek.sh

OUTPUT_ROOT="./prepared"
PIPELINE_ROOT="${OUTPUT_ROOT}/pipeline"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_DIR="${OUTPUT_ROOT}/logs"
mkdir -p "${LOG_DIR}" "${PIPELINE_ROOT}"

SELECTED_DATASET="${1:-}"
if [[ -z "${SELECTED_DATASET}" ]]; then
  echo "Usage: bash 2_run_videotree_pipeline.sh <dataset>"
  echo "Allowed datasets: lvb | lvbench | videomme | mlvu"
  exit 1
fi

LOG_FILE="${LOG_DIR}/${TIMESTAMP}_2_run_videotree_pipeline_${SELECTED_DATASET}.log"
exec > >(tee -a "${LOG_FILE}") 2>&1
echo "Logging to ${LOG_FILE}"

# VLM/LLM server config (OpenAI-compatible, e.g. vLLM)
BASE_URL="http://127.0.0.1:8005/v1"
API_KEY="EMPTY"
MODEL_NAME="Qwen/Qwen3-VL-4B-Instruct"
REQUEST_TIMEOUT="5"
MAX_RETRIES="2"

# Feature directories (.pt per sample), generated by:
#   1_5_generate_frame_features.sh
LVB_FRAME_FEAT_PATH="./prepared/frame_features/lvb"
LVBENCH_FRAME_FEAT_PATH="./prepared/frame_features/lvbench"
VIDEOMME_FRAME_FEAT_PATH="./prepared/frame_features/videomme"
MLVU_FRAME_FEAT_PATH="./prepared/frame_features/mlvu"

# If >0, run only first N examples
NUM_EXAMPLES_TO_RUN="-1"

run_one_dataset() {
  local dataset_name="$1"
  local frame_feat_path="$2"
  local prepared_dir="${OUTPUT_ROOT}/${dataset_name}"
  local out_dir="${PIPELINE_ROOT}/${dataset_name}"

  local data_path="${prepared_dir}/data.json"
  local anno_path="${prepared_dir}/anno.json"
  local duration_path="${prepared_dir}/duration.json"

  local stage1_dir="${out_dir}/stage1_breadth"
  local stage2_dir="${out_dir}/stage2_depth"
  local stage3_dir="${out_dir}/stage3_qa"

  local relevance_path="${stage1_dir}/relevance_score.json"
  local width_res_path="${stage1_dir}/width_res.json"
  local depth_idx_path="${stage2_dir}/depth_expansion_res.json"

  mkdir -p "${stage1_dir}" "${stage2_dir}" "${stage3_dir}"

  if [[ ! -f "${data_path}" || ! -f "${anno_path}" || ! -f "${duration_path}" ]]; then
    echo "Missing prepared files for ${dataset_name}. Expected:"
    echo "  ${data_path}"
    echo "  ${anno_path}"
    echo "  ${duration_path}"
    exit 1
  fi

  if [[ ! -d "${frame_feat_path}" ]]; then
    echo "Frame feature directory not found for ${dataset_name}: ${frame_feat_path}"
    exit 1
  fi

  echo ""
  echo "================ ${dataset_name}: Stage 1 (Adaptive Breadth Expansion) ================"
  python adaptive_breath_expansion.py \
    --dataset egoschema \
    --data_path "${data_path}" \
    --anno_path "${anno_path}" \
    --duration_path "${duration_path}" \
    --frame_feat_path "${frame_feat_path}" \
    --output_base_path "${stage1_dir}" \
    --output_filename "relevance_score.json" \
    --model "${MODEL_NAME}" \
    --backend openai \
    --base_url "${BASE_URL}" \
    --api_key "${API_KEY}" \
    --request_timeout "${REQUEST_TIMEOUT}" \
    --max_retries "${MAX_RETRIES}" \
    --prompt_type cap_score \
    --num_examples_to_run "${NUM_EXAMPLES_TO_RUN}"

  echo ""
  echo "================ ${dataset_name}: Stage 2 (Relevance-guided Depth Expansion) ================"
  python - "${relevance_path}" "${width_res_path}" "${frame_feat_path}" "${depth_idx_path}" <<'PY'
import json
import os
import sys
import torch

from depth_expansion import (
    hierarchical_clustering_with_external_primary,
    find_closest_points_in_temporal_order_subsub,
)

relevance_path = sys.argv[1]
width_res_path = sys.argv[2]
frame_feat_path = sys.argv[3]
depth_idx_path = sys.argv[4]

with open(relevance_path, "r") as f:
    relevance_raw = json.load(f)

if isinstance(relevance_raw, dict) and "data" in relevance_raw:
    relevance_data = relevance_raw["data"]
else:
    relevance_data = relevance_raw

with open(width_res_path, "r") as f:
    width_res_data = json.load(f)

width_cluster_id_dict = {item["name"]: item["cluster_ids_x"] for item in width_res_data}

all_data = []
missing_feats = 0
for uid, item in relevance_data.items():
    feat_file = os.path.join(frame_feat_path, f"{uid}.pt")
    if not os.path.exists(feat_file):
        missing_feats += 1
        continue

    try:
        img_feats = torch.load(feat_file).cpu()
        relevance_scores = item.get("pred", [])
        primary_cluster_ids = width_cluster_id_dict.get(uid, None)
        if primary_cluster_ids is None or not isinstance(relevance_scores, list):
            continue

        clusters_info = hierarchical_clustering_with_external_primary(
            img_feats,
            primary_cluster_ids,
            relevance_scores,
            num_subclusters=4,
            num_subsubclusters=4,
        )
        closest_points = find_closest_points_in_temporal_order_subsub(
            img_feats, clusters_info, relevance_scores
        )
        all_data.append(
            {"name": uid, "sorted_values": closest_points, "relevance": relevance_scores}
        )
    except Exception as e:
        print(f"[WARN] failed depth expansion for {uid}: {e}")

os.makedirs(os.path.dirname(depth_idx_path), exist_ok=True)
with open(depth_idx_path, "w") as f:
    json.dump(all_data, f, indent=2)

print(f"Wrote depth index for {len(all_data)} samples to {depth_idx_path}")
if missing_feats > 0:
    print(f"[WARN] missing frame features for {missing_feats} samples")
PY

  echo ""
  echo "================ ${dataset_name}: Stage 3 (LLM Reasoning / QA) ================"
  python main_qa.py \
    --dataset egoschema \
    --data_path "${data_path}" \
    --anno_path "${anno_path}" \
    --duration_path "${duration_path}" \
    --tree_node_idx "${depth_idx_path}" \
    --output_base_path "${stage3_dir}" \
    --output_filename "qa.json" \
    --model "${MODEL_NAME}" \
    --backend openai \
    --base_url "${BASE_URL}" \
    --api_key "${API_KEY}" \
    --request_timeout "${REQUEST_TIMEOUT}" \
    --max_retries "${MAX_RETRIES}" \
    --prompt_type qa_standard \
    --num_examples_to_run "${NUM_EXAMPLES_TO_RUN}"

  echo "Completed ${dataset_name}"
}

case "${SELECTED_DATASET}" in
  lvb)
    run_one_dataset "lvb" "${LVB_FRAME_FEAT_PATH}"
    ;;
  lvbench)
    run_one_dataset "lvbench" "${LVBENCH_FRAME_FEAT_PATH}"
    ;;
  videomme)
    run_one_dataset "videomme" "${VIDEOMME_FRAME_FEAT_PATH}"
    ;;
  mlvu)
    run_one_dataset "mlvu" "${MLVU_FRAME_FEAT_PATH}"
    ;;
  *)
    echo "Invalid dataset: ${SELECTED_DATASET}"
    echo "Allowed datasets: lvb | lvbench | videomme | mlvu"
    exit 1
    ;;
esac

echo ""
echo "Done. Outputs are under: ${PIPELINE_ROOT}/${SELECTED_DATASET}/stage{1,2,3}_*"

notify.py "VideoTree pipeline completed for ${SELECTED_DATASET}"